name: zizmor 🌈

on:
  push:
    branches:
      - master
    paths:
      - .github/**.yml
      - .github/**.yaml
      - actions/**.yml
      - actions/**.yaml
  pull_request:
    paths:
      - .github/**.yml
      - .github/**.yaml
      - actions/**.yml
      - actions/**.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    permissions:
      contents: read
    uses: ./.github/workflows/zizmor.yml
    with:
      advanced-security: false
      annotations: true
      audit-inputs: .github actions
      persona: pedantic
