name: zizmor 🌈

on:
  pull_request:
    paths: &security-paths
      - .github/**.yml
      - .github/**.yaml
      - actions/**.yml
      - actions/**.yaml
  push:
    branches:
      - master
    paths: *security-paths

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    uses: yiisoft/actions/.github/workflows/zizmor.yml@master
