name: zizmor 🌈

on:
  pull_request:
    paths: &security-paths
      - .github/**.yml
      - .github/**.yaml
      - actions/**.yml
      - actions/**.yaml
  push:
    branches:
      - master
    paths: *security-paths

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Analyze
    permissions:
      contents: read
    uses: ./.github/workflows/zizmor.yml
    with:
      advanced-security: false
      annotations: true
      audit-inputs: .github actions
      persona: pedantic
