name: GitHub Actions Security Analysis.

on:
  workflow_call:
    inputs:
      advanced-security:
        description: Upload SARIF results to GitHub Advanced Security.
        default: false
        required: false
        type: boolean
      annotations:
        description: Emit GitHub Actions annotations.
        default: true
        required: false
        type: boolean
      persona:
        description: zizmor persona to use while auditing.
        default: pedantic
        required: false
        type: string

permissions:
  contents: read

jobs:
  zizmor:
    name: Run zizmor 🌈.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Run zizmor 🌈.
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: ${{ inputs.advanced-security }}
          annotations: ${{ inputs.annotations }}
          persona: ${{ inputs.persona }}
